FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    procps \
    libexpat1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    numpy \
    tifffile \
    imagecodecs \
    pillow \
    scikit-image \
    rasterio \
    shapely

ENV PYTHONUNBUFFERED=1

CMD ["/bin/bash"]
